package com.example.walkfie;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast; // Keep Toast for interaction feedback

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;

import com.bumptech.glide.Glide; // Import Glide for image loading
import com.google.firebase.firestore.ServerTimestamp; // Import if you plan to use this annotation in PostItem (for saving new posts)

import java.util.Date; // For Firestore Timestamp
import java.util.List;
import java.util.concurrent.TimeUnit; // For time formatting

public class PostAdapter extends RecyclerView.Adapter<PostAdapter.PostViewHolder> {

    // --- PostItem Class Updated for Firestore Compatibility ---
    public static class PostItem {
        private String id; // Firestore document ID
        private String userId; // User who made the post (useful for fetching profile details)
        private String username;
        private String description;
        private String imageUrl; // URL of the post image from Firebase Storage
        private String userProfilePicUrl; // URL of the poster's profile picture
        private long likesCount; // Changed to long to match Firestore Number type
        private long commentsCount; // Changed to long
        private Date timestamp; // Use java.util.Date for Firestore Timestamp

        // IMPORTANT: Public no-argument constructor needed for Firestore's automatic object mapping
        public PostItem() {}

        // Constructor for creating a new PostItem locally before uploading to Firestore
        // Note: 'id' is not passed here as it's generated by Firestore
        public PostItem(String userId, String username, String description, String imageUrl,
                        String userProfilePicUrl, long likesCount, long commentsCount, Date timestamp) {
            this.userId = userId;
            this.username = username;
            this.description = description;
            this.imageUrl = imageUrl;
            this.userProfilePicUrl = userProfilePicUrl;
            this.likesCount = likesCount;
            this.commentsCount = commentsCount;
            this.timestamp = timestamp;
        }

        // --- Getters (required by Firestore for deserialization) ---
        public String getId() { return id; }
        public String getUserId() { return userId; }
        public String getUsername() { return username; }
        public String getDescription() { return description; }
        public String getImageUrl() { return imageUrl; }
        public String getUserProfilePicUrl() { return userProfilePicUrl; }
        public long getLikesCount() { return likesCount; }
        public long getCommentsCount() { return commentsCount; }

        // @ServerTimestamp annotation can be placed here IF you want Firestore to
        // automatically set the timestamp when you save a new PostItem using .add() or .set()
        // If you set the timestamp manually in the app before saving (e.g., new Date()), it will overwrite this.
        // It's generally good practice to let Firestore handle server-side timestamps.
        public Date getTimestamp() { return timestamp; }


        // --- Setters (Firestore uses these internally) ---
        public void setId(String id) { this.id = id; }
        public void setUserId(String userId) { this.userId = userId; }
        public void setUsername(String username) { this.username = username; }
        public void setDescription(String description) { this.description = description; }
        public void setImageUrl(String imageUrl) { this.imageUrl = imageUrl; }
        public void setUserProfilePicUrl(String userProfilePicUrl) { this.userProfilePicUrl = userProfilePicUrl; }
        public void setLikesCount(long likesCount) { this.likesCount = likesCount; }
        public void setCommentsCount(long commentsCount) { this.commentsCount = commentsCount; }
        public void setTimestamp(Date timestamp) { this.timestamp = timestamp; }


        /**
         * Helper method to format the timestamp into a human-readable string (e.g., "5m ago", "2h ago", "yesterday", "June 15")
         */
        public String getFormattedTime() {
            if (timestamp == null) {
                return "";
            }

            long currentTime = System.currentTimeMillis();
            long postTimeMillis = timestamp.getTime();
            long diff = currentTime - postTimeMillis;

            if (diff < TimeUnit.MINUTES.toMillis(1)) {
                return "Just now";
            } else if (diff < TimeUnit.HOURS.toMillis(1)) {
                return TimeUnit.MILLISECONDS.toMinutes(diff) + "m ago";
            } else if (diff < TimeUnit.DAYS.toMillis(1)) {
                return TimeUnit.MILLISECONDS.toHours(diff) + "h ago";
            } else if (diff < TimeUnit.DAYS.toMillis(7)) {
                long days = TimeUnit.MILLISECONDS.toDays(diff);
                return days + (days == 1 ? " day ago" : " days ago");
            } else {
                // Format for dates older than a week
                // Example: June 15, 2025 (or simpler: Jun 15)
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("MMM dd", java.util.Locale.getDefault());
                return sdf.format(timestamp);
            }
        }
    }
    // --- End of PostItem Class Update ---


    private List<PostItem> postList;
    private OnPostInteractionListener onPostInteractionListener;

    public interface OnPostInteractionListener {
        void onProfileClick(PostItem postItem);
        void onLikeClick(PostItem postItem);
        void onCommentClick(PostItem postItem);
        void onShareClick(PostItem postItem);
        void onSaveClick(PostItem postItem);
        void onViewCommentsClick(PostItem postItem);
        void onPostOptionsClick(PostItem postItem);
    }

    public PostAdapter(List<PostItem> postList, OnPostInteractionListener onPostInteractionListener) {
        this.postList = postList;
        this.onPostInteractionListener = onPostInteractionListener;
    }

    @NonNull
    @Override
    public PostViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_post_ulit, parent, false);
        return new PostViewHolder(view);
    }

    @Override
    public void onBindViewHolder(@NonNull PostViewHolder holder, int position) {
        PostItem postItem = postList.get(position);

        // --- Bind data from PostItem (now from Firestore) ---
        holder.tvPostUsername.setText(postItem.getUsername());
        holder.tvLikesCount.setText(postItem.getLikesCount() + " likes"); // Format long to String
        holder.tvPostDescription.setText(postItem.getDescription());
        holder.tvViewAllComments.setText("View all " + postItem.getCommentsCount() + " comments");
        holder.tvPostTime.setText(postItem.getFormattedTime()); // Use the formatted time

        // --- Load images using Glide ---
        // Load Profile Picture
        if (postItem.getUserProfilePicUrl() != null && !postItem.getUserProfilePicUrl().isEmpty()) {
            Glide.with(holder.itemView.getContext())
                    .load(postItem.getUserProfilePicUrl())
                    .placeholder(R.drawable.ic_default_profile_placeholder) // Your placeholder image
                    .error(R.drawable.ic_default_profile_placeholder) // Image to show if loading fails
                    .into(holder.ivPostProfilePic);
        } else {
            holder.ivPostProfilePic.setImageResource(R.drawable.ic_default_profile_placeholder); // Fallback to local drawable
        }

        // Load Post Content Image
        if (postItem.getImageUrl() != null && !postItem.getImageUrl().isEmpty()) {
            Glide.with(holder.itemView.getContext())
                    .load(postItem.getImageUrl())
                    .placeholder(R.drawable.sample_story_placeholder) // Your placeholder image
                    .error(R.drawable.sample_story_placeholder) // Image to show if loading fails
                    .into(holder.ivPostContent);
        } else {
            holder.ivPostContent.setImageResource(R.drawable.sample_story_placeholder); // Fallback to local drawable
        }

        // --- Set click listeners (remain largely the same, operating on the PostItem object) ---
        holder.ivPostProfilePic.setOnClickListener(v -> {
            if (onPostInteractionListener != null) onPostInteractionListener.onProfileClick(postItem);
        });
        holder.tvPostUsername.setOnClickListener(v -> {
            if (onPostInteractionListener != null) onPostInteractionListener.onProfileClick(postItem);
        });
        holder.ivLike.setOnClickListener(v -> {
            if (onPostInteractionListener != null) onPostInteractionListener.onLikeClick(postItem);
        });
        holder.ivComment.setOnClickListener(v -> {
            if (onPostInteractionListener != null) onPostInteractionListener.onCommentClick(postItem);
        });
        holder.ivShare.setOnClickListener(v -> {
            if (onPostInteractionListener != null) onPostInteractionListener.onShareClick(postItem);
        });
        holder.ivSave.setOnClickListener(v -> {
            if (onPostInteractionListener != null) onPostInteractionListener.onSaveClick(postItem);
        });
        holder.tvViewAllComments.setOnClickListener(v -> {
            if (onPostInteractionListener != null) onPostInteractionListener.onViewCommentsClick(postItem);
        });
        holder.ivPostOptions.setOnClickListener(v -> {
            if (onPostInteractionListener != null) onPostInteractionListener.onPostOptionsClick(postItem);
        });
    }

    @Override
    public int getItemCount() {
        return postList.size();
    }

    // --- New method to update the adapter's data list ---
    public void updatePosts(List<PostItem> newPostList) {
        // Clearing and adding all is a simple way to update.
        // For performance in large lists, consider DiffUtil.
        this.postList.clear();
        this.postList.addAll(newPostList);
        notifyDataSetChanged(); // Notify the RecyclerView that the data has changed
    }

    static class PostViewHolder extends RecyclerView.ViewHolder {
        ImageView ivPostProfilePic, ivPostContent, ivLike, ivComment, ivShare, ivSave, ivPostOptions;
        TextView tvPostUsername, tvLikesCount, tvPostDescription, tvViewAllComments, tvPostTime;

        public PostViewHolder(@NonNull View itemView) {
            super(itemView);
            ivPostProfilePic = itemView.findViewById(R.id.ivPostProfilePic);
            ivPostContent = itemView.findViewById(R.id.ivPostContent);
            ivLike = itemView.findViewById(R.id.ivLike);
            ivComment = itemView.findViewById(R.id.ivComment);
            ivShare = itemView.findViewById(R.id.ivShare);
            ivSave = itemView.findViewById(R.id.ivSave);
            ivPostOptions = itemView.findViewById(R.id.ivPostOptions);

            tvPostUsername = itemView.findViewById(R.id.tvPostUsername);
            tvLikesCount = itemView.findViewById(R.id.tvLikesCount);
            tvPostDescription = itemView.findViewById(R.id.tvPostDescription);
            tvViewAllComments = itemView.findViewById(R.id.tvViewAllComments);
            tvPostTime = itemView.findViewById(R.id.tvPostTime);
        }
    }
}